CREATE TABLE REGRAPRECO(
ID INT PRIMARY KEY,
DIAS VARCHAR(20),
PERIODO VARCHAR(20),
VALOR DOUBLE);

CREATE TABLE VEICULO (
ID_VEICULO INT PRIMARY KEY,
ID_VOUCHER INT,
PLACA VARCHAR(8),
MODELO VARCHAR(20),
COR VARCHAR(10),
FOREIGN KEY (ID_VOUCHER) REFERENCES VOUCHER(ID));

CREATE TABLE  VOUCHER(
ID_VOUCHER INT PRIMARY KEY,
ID_VEICULO INT,
ENTRADA DATETIME,
SAIDA DATETIME,
PRECO DOUBLE,
FOREIGN KEY (ID_VEICULO) REFERENCES VEICULO(ID));
